# copy into ~/.config
# Replace the "❯" symbol in the prompt with "➜"
[character]      # The name of the module we are configuring is "character"
success_symbol = "➜ "
error_symbol = "✗ "

[kubernetes]
disabled = false
symbol = "☸ "
style = "bold blue"


format = """\
    $username\
    $hostname\
    $directory\
    $git_branch\
    $git_state\
    $git_status\
    $package\
    $golang\
    $java\
    $nodejs\
    $rust\
    $nix_shell\
    $aws\
    $env_var\
    $cmd_duration\
    $line_break\
    $jobs\
    $kubernetes\
    $character\
"""

